import { Message, Task, PlatformStatus, Statistics } from './types'

const now = new Date()

export const mockMessages: Message[] = [
  {
    id: '1',
    platform: 'qq',
    sender: '李老师',
    groupName: '数据结构课程群',
    content: '同学们注意，本周五（5月9日）下午6点前提交实验报告三，逾期不候！',
    timestamp: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-09T18:00:00'),
    extractedTask: '提交数据结构实验报告三',
    isRead: false,
  },
  {
    id: '2',
    platform: 'wechat',
    sender: '社团主席-小明',
    groupName: '编程社团群',
    content: '下周三（5月13日）晚上7点在A301教室开会，讨论编程马拉松的筹备工作，请大家准时参加',
    timestamp: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-13T19:00:00'),
    extractedTask: '参加编程社团会议 - A301教室',
    isRead: true,
  },
  {
    id: '3',
    platform: 'feishu',
    sender: '实习HR-张姐',
    groupName: '腾讯实习群',
    content: '请各位实习生在本月10日前完成入职材料的提交，包括身份证复印件、学生证复印件等',
    timestamp: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-10T23:59:00'),
    extractedTask: '提交腾讯实习入职材料',
    isRead: false,
  },
  {
    id: '4',
    platform: 'qq',
    sender: '班长小红',
    groupName: '计科2班群',
    content: '下周一（5月11日）早上8点在图书馆集合，一起去拍毕业照！别迟到哦～',
    timestamp: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-11T08:00:00'),
    extractedTask: '图书馆集合拍毕业照',
    isRead: true,
  },
  {
    id: '5',
    platform: 'wechat',
    sender: '导师王教授',
    groupName: '毕业论文指导群',
    content: '论文终稿提交截止日期是5月15日，请大家抓紧时间修改，有问题随时联系我',
    timestamp: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-15T23:59:00'),
    extractedTask: '提交毕业论文终稿',
    isRead: false,
  },
  {
    id: '6',
    platform: 'feishu',
    sender: '项目组长',
    groupName: '创新项目组',
    content: '明天（5月7日）下午3点进行项目中期汇报，请准备好PPT和演示Demo',
    timestamp: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-07T15:00:00'),
    extractedTask: '项目中期汇报 - 准备PPT和Demo',
    isRead: false,
  },
  {
    id: '7',
    platform: 'qq',
    sender: '辅导员刘老师',
    groupName: '年级通知群',
    content: '提醒：本学期学费缴纳截止日期为5月20日，请还未缴费的同学尽快办理',
    timestamp: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    hasDeadline: true,
    extractedDeadline: new Date('2026-05-20T23:59:00'),
    extractedTask: '缴纳本学期学费',
    isRead: true,
  },
]

export const mockTasks: Task[] = [
  {
    id: 't1',
    title: '项目中期汇报 - 准备PPT和Demo',
    description: '明天下午3点进行项目中期汇报，需要准备演示材料',
    deadline: new Date('2026-05-07T15:00:00'),
    priority: 'high',
    status: 'in_progress',
    source: {
      platform: 'feishu',
      messageId: '6',
      sender: '项目组长',
    },
    createdAt: new Date(now.getTime() - 1 * 60 * 60 * 1000),
    tags: ['项目', '汇报'],
  },
  {
    id: 't2',
    title: '提交数据结构实验报告三',
    description: '本周五下午6点前提交',
    deadline: new Date('2026-05-09T18:00:00'),
    priority: 'high',
    status: 'pending',
    source: {
      platform: 'qq',
      messageId: '1',
      sender: '李老师',
    },
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000),
    tags: ['作业', '课程'],
  },
  {
    id: 't3',
    title: '提交腾讯实习入职材料',
    description: '身份证复印件、学生证复印件等',
    deadline: new Date('2026-05-10T23:59:00'),
    priority: 'high',
    status: 'pending',
    source: {
      platform: 'feishu',
      messageId: '3',
      sender: '实习HR-张姐',
    },
    createdAt: new Date(now.getTime() - 6 * 60 * 60 * 1000),
    tags: ['实习', '材料'],
  },
  {
    id: 't4',
    title: '图书馆集合拍毕业照',
    description: '下周一早上8点',
    deadline: new Date('2026-05-11T08:00:00'),
    priority: 'medium',
    status: 'pending',
    source: {
      platform: 'qq',
      messageId: '4',
      sender: '班长小红',
    },
    createdAt: new Date(now.getTime() - 8 * 60 * 60 * 1000),
    tags: ['活动', '毕业'],
  },
  {
    id: 't5',
    title: '参加编程社团会议',
    description: 'A301教室，讨论编程马拉松筹备',
    deadline: new Date('2026-05-13T19:00:00'),
    priority: 'medium',
    status: 'pending',
    source: {
      platform: 'wechat',
      messageId: '2',
      sender: '社团主席-小明',
    },
    createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000),
    tags: ['社团', '会议'],
  },
  {
    id: 't6',
    title: '提交毕业论文终稿',
    description: '联系导师确认最终版本',
    deadline: new Date('2026-05-15T23:59:00'),
    priority: 'high',
    status: 'pending',
    source: {
      platform: 'wechat',
      messageId: '5',
      sender: '导师王教授',
    },
    createdAt: new Date(now.getTime() - 12 * 60 * 60 * 1000),
    tags: ['论文', '毕业'],
  },
  {
    id: 't7',
    title: '缴纳本学期学费',
    description: '截止日期5月20日',
    deadline: new Date('2026-05-20T23:59:00'),
    priority: 'low',
    status: 'pending',
    source: {
      platform: 'qq',
      messageId: '7',
      sender: '辅导员刘老师',
    },
    createdAt: new Date(now.getTime() - 24 * 60 * 60 * 1000),
    tags: ['缴费', '学校'],
  },
]

export const mockPlatformStatus: PlatformStatus[] = [
  {
    platform: 'qq',
    isConnected: true,
    lastSync: new Date(now.getTime() - 5 * 60 * 1000),
    messageCount: 1247,
    unreadCount: 23,
  },
  {
    platform: 'wechat',
    isConnected: true,
    lastSync: new Date(now.getTime() - 3 * 60 * 1000),
    messageCount: 892,
    unreadCount: 15,
  },
  {
    platform: 'feishu',
    isConnected: true,
    lastSync: new Date(now.getTime() - 2 * 60 * 1000),
    messageCount: 456,
    unreadCount: 8,
  },
]

export const mockStatistics: Statistics = {
  totalTasks: 7,
  completedTasks: 0,
  upcomingDeadlines: 7,
  overdueCount: 0,
  messagesSynced: 2595,
  platformStats: [
    { platform: 'qq', tasks: 3, messages: 1247 },
    { platform: 'wechat', tasks: 2, messages: 892 },
    { platform: 'feishu', tasks: 2, messages: 456 },
  ],
}

export const weeklyActivityData = [
  { day: '周一', messages: 420, tasks: 8 },
  { day: '周二', messages: 380, tasks: 6 },
  { day: '周三', messages: 510, tasks: 12 },
  { day: '周四', messages: 450, tasks: 9 },
  { day: '周五', messages: 620, tasks: 15 },
  { day: '周六', messages: 180, tasks: 3 },
  { day: '周日', messages: 150, tasks: 2 },
]

export const aiSuggestions = [
  {
    id: 's1',
    type: 'urgent',
    title: '紧急提醒',
    content: '明天下午3点有项目中期汇报，建议今晚完成PPT制作，预留明天上午进行最后检查。',
    actionText: '查看任务详情',
  },
  {
    id: 's2',
    type: 'optimize',
    title: '日程优化建议',
    content: '检测到本周五有2个截止任务，建议将实验报告的完成时间提前到周四，避免时间冲突。',
    actionText: '调整日程',
  },
  {
    id: 's3',
    type: 'reminder',
    title: '别忘了准备材料',
    content: '腾讯实习入职材料截止日期临近，建议今天准备好所需证件复印件。',
    actionText: '查看清单',
  },
]
